/**
 * Notification System Constants
 */

export const NOTIFICATION_LIMITS = {
    MAX_TITLE_LENGTH: 255,
    MAX_MESSAGE_LENGTH: 5000,
    MAX_ACTION_TEXT_LENGTH: 100,
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
} as const;

export const NOTIFICATION_CHANNELS = {
    EMAIL: 'email',
    SMS: 'sms',
    IN_APP: 'in_app',
    PUSH: 'push',
} as const;

export const TEMPLATE_CODES = {
    ORDER_CREATED: 'ORDER_CREATED',
    ORDER_PAID: 'ORDER_PAID',
    ORDER_SHIPPED: 'ORDER_SHIPPED',
    ORDER_DELIVERED: 'ORDER_DELIVERED',
    ORDER_CANCELLED: 'ORDER_CANCELLED',
    NEW_ORDER_RECEIVED: 'NEW_ORDER_RECEIVED',
    PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    LOW_STOCK_ALERT: 'LOW_STOCK_ALERT',
    OUT_OF_STOCK_ALERT: 'OUT_OF_STOCK_ALERT',
    USER_WELCOME: 'USER_WELCOME',
} as const;
