/**
 * Notification System Constants
 */

export const NOTIFICATION_LIMITS = {
    MAX_TITLE_LENGTH: 255,
    MAX_MESSAGE_LENGTH: 5000,
    MAX_ACTION_TEXT_LENGTH: 100,
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
} as const;

export const NOTIFICATION_CHANNELS = {
    EMAIL: 'email',
    SMS: 'sms',
    IN_APP: 'in_app',
    PUSH: 'push',
} as const;

export const TEMPLATE_CODES = {
    // Order lifecycle templates
    ORDER_CREATED: 'ORDER_CREATED',
    ORDER_CONFIRMED: 'ORDER_CONFIRMED',
    ORDER_PAID: 'ORDER_PAID',
    ORDER_SHIPPED: 'ORDER_SHIPPED',
    ORDER_DELIVERED: 'ORDER_DELIVERED',
    ORDER_CANCELLED: 'ORDER_CANCELLED',

    // Order updates
    ORDER_TRACKING_UPDATED: 'ORDER_TRACKING_UPDATED',
    ORDER_PAYMENT_CONFIRMED: 'ORDER_PAYMENT_CONFIRMED',
    ORDER_FULFILLMENT_UPDATED: 'ORDER_FULFILLMENT_UPDATED',

    // Admin notifications
    NEW_ORDER_RECEIVED: 'NEW_ORDER_RECEIVED',

    // Payment templates
    PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',

    // Inventory templates
    LOW_STOCK_ALERT: 'LOW_STOCK_ALERT',
    OUT_OF_STOCK_ALERT: 'OUT_OF_STOCK_ALERT',

    // User templates
    USER_WELCOME: 'USER_WELCOME',
} as const;
