/**
 * POST /api/admins
 * Create a new admin/staff user
 */

import { Router, Response } from 'express';
import { z } from 'zod';
import { RequestWithUser } from '../../../interfaces';
import { requireAuth, requirePermission, validationMiddleware } from '../../../middlewares';
import { ResponseFormatter, shortTextSchema, emailSchema, HttpException, logger } from '../../../utils';
import { db } from '../../../database';
import { eq, and } from 'drizzle-orm';
import { users } from '../../user/shared/user.schema';
import { adminProfiles } from '../shared/admin-profiles.schema';
import { syncTags } from '../../tags/services/tag-sync.service';

// Validation Schema
const createAdminSchema = z.object({
    // Required User Fields
    first_name: shortTextSchema,
    middle_name: shortTextSchema.optional(),
    last_name: shortTextSchema,
    email: emailSchema,
    phone_number: z.string().optional(),
    secondary_email: z.string().email().optional(),
    secondary_phone_number: z.string().optional(),
    tags: z.array(z.string()).optional(),
    profile_image_url: z.string().optional(),

    // Optional User Fields
    display_name: z.string().max(100).optional(),
    date_of_birth: z.string().optional(),
    gender: z.enum(['male', 'female', 'other', 'prefer_not_to_say']).optional(),
    preferred_language: z.string().optional(),
    languages: z.array(z.string()).optional(),

    // Admin Profile Fields
    employee_id: z.string().max(50).optional(),
    department: z.string().max(100).optional(),
    job_title: z.string().max(100).optional(),
    is_active: z.boolean().default(true),
});

type CreateAdminDto = z.infer<typeof createAdminSchema>;

const handler = async (req: RequestWithUser, res: Response) => {
    const data: CreateAdminDto = req.body;

    logger.info('Creating new admin', { email: data.email });

    // Check if user already exists
    const [existingUser] = await db
        .select()
        .from(users)
        .where(eq(users.email, data.email));

    if (existingUser) {
        throw new HttpException(409, 'A user with this email already exists');
    }

    // Check if employee_id already exists (if provided)
    if (data.employee_id) {
        const [existingEmployee] = await db
            .select()
            .from(adminProfiles)
            .where(eq(adminProfiles.employee_id, data.employee_id));

        if (existingEmployee) {
            throw new HttpException(409, 'An admin with this employee ID already exists');
        }
    }

    // Check if email was verified via OTP
    const { emailOtps } = await import('../../user/shared/email-otp.schema');
    const [verifiedOtp] = await db
        .select()
        .from(emailOtps)
        .where(
            and(
                eq(emailOtps.email, data.email.toLowerCase()),
                eq(emailOtps.purpose, 'email_verification'),
            )
        )
        .limit(1);

    const isEmailVerified = verifiedOtp?.verified_at !== null;
    const emailVerifiedAt = verifiedOtp?.verified_at || null;

    // Check if secondary email was verified via OTP
    let isSecondaryEmailVerified = false;
    if (data.secondary_email) {
        const [secondaryVerifiedOtp] = await db
            .select()
            .from(emailOtps)
            .where(
                and(
                    eq(emailOtps.email, data.secondary_email.toLowerCase()),
                    eq(emailOtps.purpose, 'email_verification'),
                )
            )
            .limit(1);
        isSecondaryEmailVerified = secondaryVerifiedOtp?.verified_at !== null;
    }

    await db.transaction(async (tx) => {
        // 1. Create User Record
        const [user] = await tx
            .insert(users)
            .values({
                first_name: data.first_name,
                middle_name: data.middle_name || null,
                last_name: data.last_name,
                email: data.email.toLowerCase(),
                phone_number: data.phone_number || null,
                secondary_email: data.secondary_email?.toLowerCase() || null,
                secondary_phone_number: data.secondary_phone_number || null,
                secondary_email_verified: isSecondaryEmailVerified,
                display_name: data.display_name || null,
                date_of_birth: data.date_of_birth || null,
                gender: data.gender || null,
                tags: data.tags || [],
                profile_image_url: data.profile_image_url || null,
                preferred_language: data.preferred_language || 'en',
                languages: data.languages || [],
                email_verified: isEmailVerified,
                email_verified_at: emailVerifiedAt,
                // No user_type set (deprecated field, nullable now)
                // No display_id set yet (will be auto-generated by migration trigger)
            })
            .returning();

        if (!user) {
            throw new HttpException(500, 'Failed to create user');
        }

        // 2. Create Admin Profile
        const [adminProfile] = await tx
            .insert(adminProfiles)
            .values({
                user_id: user.id,
                employee_id: data.employee_id || null,
                department: data.department || null,
                job_title: data.job_title || null,
                is_active: data.is_active,
            })
            .returning();

        if (!adminProfile) {
            throw new HttpException(500, 'Failed to create admin profile');
        }

        // 3. Sync tags
        if (data.tags && data.tags.length > 0) {
            await syncTags(data.tags);
        }

        logger.info(`Admin created successfully: ${user.id}`);

        // Format response
        const response = {
            id: user.id,
            auth_id: user.auth_id,
            display_id: user.display_id,
            first_name: user.first_name,
            middle_name: user.middle_name,
            last_name: user.last_name,
            email: user.email,
            phone_number: user.phone_number,
            email_verified: user.email_verified,
            profile_image_url: user.profile_image_url,
            created_at: user.created_at,
            profile: adminProfile,
        };

        ResponseFormatter.success(res, response, 'Admin created successfully', 201);
    });
};

const router = Router();
router.post(
    '/',
    requireAuth,
    requirePermission('admins:create'),
    validationMiddleware(createAdminSchema, 'body'),
    handler
);

export default router;
